In [ ]:
Entrenamiento en ciencia de datos pinto 77

In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

ruta = "Activos_Informacion_UFPS_Ocana.csv"

df = pd.read_csv(ruta, sep=",")

In [7]:
#1.Conocer los datos
print(df.shape)  # filas y columnas

(66669, 10)

In [8]:
df.info()   # tipos, nulos y memoria

<class 'pandas.DataFrame'>
RangeIndex: 66669 entries, 0 to 66668
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   PROCESO                           66669 non-null  str
 1   ACTIVO                            66669 non-null  str
 2   DESCRIPCION                       66386 non-null  str
 3   DUENO_ DEL_ACTIVO                 66669 non-null  str
 4   TIPO_DE_ACTIVO                    66669 non-null  str
 5   IDIOMA                            66669 non-null  str
 6   MEDIO_DE_CONSERVACION_Y_O_SOPRTE  66669 non-null  str
 7   FORMATO                           65426 non-null  str
 8   DISPONIBLE                        66669 non-null  str
 9   PUBLICADA                         66669 non-null  bool
dtypes: bool(1), str(9)
memory usage: 4.6 MB

In [10]:
display(df.head()) #primeras 5 filas

,PROCESO,ACTIVO,DESCRIPCION,DUENO_ DEL_ACTIVO,TIPO_DE_ACTIVO,IDIOMA,MEDIO_DE_CONSERVACION_Y_O_SOPRTE,FORMATO,DISPONIBLE,PUBLICADA
0,Gestión Académica,Acta,Auditorio Barbatusco,DEPARTAMENTO INGENIERÍA MECÁNICA,INFORMACION,Español,Digital,PDF,Sí,False
1,Gestión Académica,Acta,Auditorio CIDER,DEPARTAMENTO DE CIENCIAS ADMINISTRATIVAS,INFORMACION,Español,Digital,PDF,Sí,False
2,Gestión Académica,Acta,Auditorio CIDER,GRUPO DE INVESTIGACIÓN GIDSE,INFORMACION,Español,Digital,PDF,Sí,False
3,Admisiones Registro y Control,Acta,Invitación reunión virtual: meet.google.com/fb...,OFICINA DE ADMISIONES Y REGISTRO,INFORMACION,Español,Digital,PDF,Sí,False
4,Gestión Académica,Acta,Auditorio I 202,DEPARTAMENTO INGENIERÍA MECÁNICA,INFORMACION,Español,Digital,PDF,Sí,False

In [12]:
display(df.sample(5)) # 5 filas azar

,PROCESO,ACTIVO,DESCRIPCION,DUENO_ DEL_ACTIVO,TIPO_DE_ACTIVO,IDIOMA,MEDIO_DE_CONSERVACION_Y_O_SOPRTE,FORMATO,DISPONIBLE,PUBLICADA
63137,Gestión Humana,Resolución,RECONOCIMIENTO DE BONIFICACION A NELSON AFANAD...,DIVISIÓN DE PERSONAL,INFORMACION,Español,Digital,PDF,Sí,False
19586,Gestión Académica,Oficio,Carta de Presentación - CAROLINA CASTILLAS VE...,OFICINA DE PASANTÍAS,INFORMACION,Español,Digital,PDF,Sí,False
31361,Secretaría General,Oficio,Notas registrada carga académica docente José ...,SECRETARÍA GENERAL,INFORMACION,Español,Digital,PDF,Sí,False
36590,Gestión Académica,Oficio,Notificación realización practicas de laboratorio,PLAN DE ESTUDIOS INGENIERÍA MECÁNICA,INFORMACION,Español,Digital,PDF,Sí,False
60642,Gestión Académica,Oficio,Respuesta oficio O-AC-FAA-0035,SUBDIRECCIÓN ACADÉMICA,INFORMACION,Español,Digital,PDF,Sí,False